root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
  args_bin = []
  cmd = "go build -o ./tmp/main ./cmd/api"
  run_cmd = "./tmp/main"
  exclude_dir = ["assets/static", "tmp", "tests", "node_modules", "sql"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html", "css"]
  include_file = []
  post_cmd = [
    "sqlc generate"
  ]
  pre_cmd = [
    "npm run build-css"
  ]

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"


